name: hello world - Mon premier workflow

on:
  push:               # À chaque fois que quelqu'un fait git push
    branches: [ "main" ]  # Seulement sur la branche main
  pull_request:       # À chaque fois qu'une Pull Request est ouverte/mise à jour
    branches: [ "main" ]  # Vers la branche main

jobs: 
  HelloWorld:          # Nom du job
    runs-on: ubuntu-latest  # OS sur lequel le job s'exécute

    steps:              # Étapes du job
      - name: Hello world step  # Nom de l'étape
        run: echo "Hello, world! Comment allez-vous ?"  # Commande à exécuter
      - name: Afficher la date et l'heure
        run: date  # Affiche la date et l'heure actuelles
      - name: repertoire courant
        run: pwd  # Affiche le répertoire courant
      - name: Lister les fichiers
        run: ls -la  # Liste les fichiers dans le répertoire courant
      - name: lister les variables d'environnement
        run: printenv  # Affiche les variables d'environnement